# Default values for cert-issuer.

nameOverride: ""
fullnameOverride: ""

acmeServer: "https://acme-v02.api.letsencrypt.org/directory"
ingressClass: "azure/application-gateway"

privateKeySecretRef: "letsencrypt"
