# Default values for cert-issuer.

nameOverride: ""
fullnameOverride: ""

acmeServer: "https://acme-v02.api.letsencrypt.org/directory"
ingressClass: "azure/application-gateway"

privateKeySecretRef: "letsencrypt"


# For customer dns resolver override
useDnsChallenge: false
gcpProject: ""

# Set Values for cert-issuer dependency chart
cert-manager:
  installCRDs: true
