apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.acmeServer }}
    email: {{ .Values.acmeEmail }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.privateKeySecretRef }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingressClass }}
